services:
    opcua-server:
        build:
            context: ./opcua-server
            dockerfile: Dockerfile
        ports:
            - "4840:4840"
        networks:
            - digital-twin-network
        restart: unless-stopped

    mpc-server:
        build:
            context: ./mcp-server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - digital-twin-network
        environment:
            - MCP_SERVER_PORT=8080
        depends_on:
            - opcua-server
        restart: unless-stopped

networks:
    digital-twin-network:
        driver: bridge
